// YouTube Cookie Exporter - Run this in DevTools Console
//
// Instructions:
// 1. Go to https://www.youtube.com (make sure you're logged in!)
// 2. Open DevTools: F12 or Ctrl+Shift+I
// 3. Go to Console tab
// 4. Paste ALL the code below and press Enter
// 5. Copy the output text that appears
// 6. Save it as "cookies.txt" file (Netscape format)

(function() {
  // Get all cookies from document
  const allCookies = document.cookie.split('; ');

  // Convert to Netscape format (required by yt-dlp)
  let netscapeFormat = '# Netscape HTTP Cookie File\n';
  netscapeFormat += '# Generated by YouTube Cookie Exporter\n';
  netscapeFormat += '# This file contains YouTube authentication cookies\n\n';

  allCookies.forEach(cookieStr => {
    if (cookieStr.trim()) {
      const [name, value] = cookieStr.split('=');
      // Netscape format: domain flag path secure expiration name value
      netscapeFormat += `.youtube.com\tTRUE\t/\tTRUE\t9999999999\t${name}\t${value}\n`;
    }
  });

  // Also add important YouTube authentication cookies from localStorage/sessionStorage
  console.log('%c=== YOUTUBE COOKIES EXPORTED ===', 'color: green; font-size: 16px; font-weight: bold');
  console.log('%cCopy everything below and save as cookies.txt:', 'color: blue; font-weight: bold');
  console.log('\n' + netscapeFormat);
  console.log('%c=== END OF COOKIES ===', 'color: green; font-weight: bold');
  console.log('%cNext steps:\n1. Copy all text above\n2. Create a file named "cookies.txt"\n3. Paste the content\n4. Save it to: backend_python/cookies.txt', 'color: orange; font-weight: bold');

  // Also return it for manual copying
  return netscapeFormat;
})();
